apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: archdecisionrecords.corinnekrych.org
spec:
  group: corinnekrych.org
  names:
    kind: ArchDecisionRecord
    listKind: ArchDecisionRecordList
    plural: archdecisionrecords
    singular: archdecisionrecord
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            image:
              type: string
            source:
              type: string
          required:
          - image
          - source
          type: object
        status:
          properties:
            steps:
              items:
                properties:
                  name:
                    type: string
                  phase:
                    type: string
                type: object
              type: array
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
