apiVersion: apps/v1
kind: Deployment
metadata:
  name: adr-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: adr-operator
  template:
    metadata:
      labels:
        name: adr-operator
    spec:
      serviceAccountName: adr-operator
      containers:
        - name: adr-operator
          # Replace this with the built image name
          image: quay.io/corinnekrych/adr-operator:latest
          command:
          - adr-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "adr-operator"
